name: Actions Workflow

on: [push]

jobs:
  # <--------------- RUN SEMANTIC RELEASE ---------------->
  release:
    uses: ingka-group-digital/workflows/.github/workflows/semantic-release.yml@main
    with:
      create-floating-tag: true
    secrets:
      token: ${{ secrets.RELEASE_TOKEN }}
