name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Simple javascript Actions
        id: greet 
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Shadi
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
