name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hellooooo"
      - name: multiline scripts
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

  